cpggenerator: only return `Some(frontend)` if it's actually available
Before this, we'd return the frontend and happily invoke it.
Only to then fail with a slightly different exception and a long and
confusing stacktrace:

```
Caused by: java.lang.AssertionError: assertion failed: CPG generator does not exist at: path/to/js2cpg.sh
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at io.joern.console.cpgcreation.CpgGenerator.runShellCommand$$anonfun$1(CpgGenerator.scala:30)
	at io.joern.console.cpgcreation.CpgGenerator.runShellCommand$$anonfun$adapted$1(CpgGenerator.scala:47)
	at scala.util.Try$.apply(Try.scala:217)
	at io.joern.console.cpgcreation.CpgGenerator.runShellCommand(CpgGenerator.scala:47)
	at io.joern.console.cpgcreation.JsCpgGenerator.generate(JsCpgGenerator.scala:15)
	at io.joern.console.cpgcreation.CpgGeneratorFactory.runGenerator(CpgGeneratorFactory.scala:59)
	at io.joern.console.cpgcreation.ImportCode.$anonfun$5(ImportCode.scala:212)
	at scala.Option.flatMap(Option.scala:283)
	at io.joern.console.cpgcreation.ImportCode.io$joern$console$cpgcreation$ImportCode$$apply(ImportCode.scala:210)
	at io.joern.console.cpgcreation.ImportCode.apply(ImportCode.scala:45)
```

This changes the above to a more meaningful and helpful:
```
io.joern.console.ConsoleException: No suitable CPG generator found for: /home/mp/testdata/shiftleft-js-demo/src/Controllers/Login.js
To get an overview of all available language modules, try `importCode`.
To choose a specific language, try `importCode.<language>`."
```